# Packages
brew "coreutils"
brew "curl"
brew "git"
brew "lazygit"
brew "mise"
brew "ollama"
brew "starship"
brew "wget"
brew "zsh"
brew "zoxide"

# Cask applications
cask "bruno"
cask "discord"
cask "flameshot"
cask "ghostty"
cask "raycast"
cask "whatsapp"
cask "zed"

# Fonts
cask "font-hack-nerd-font"
