[tools]
# Latest versions of each tool
rust = 'latest'
ruby = 'latest'
node = 'lts'
python = 'latest'
"cargo:eza" = "latest"
"cargo:ripgrep" = "latest"
"cargo:bat" = "latest"
"cargo:du-dust" = "latest"
"cargo:fd-find" = "latest"
"cargo:tree-sitter-cli" = "latest"

[settings]
# Always keep the downloaded archives for faster reinstalls
always_keep_download = true

# Enable experimental features
experimental = true

# Configure status display
[settings.status]
show_env = true
show_tools = true

